### ISSUE TITLE
Issue in reloading.

### ISSUE THREAD

**Issue by KDigvijay01** [codebucks27/wibe-studio#14]
Getting Error on page reload by clicking the reload button. doesn't happens at first but after doing two or three reload it happens.
in browser it says
This site can’t be reached localhost refused to connect.
Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

and in terminal it shows this
node:events:496
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (.../Desktop/wibe-studio/node_modules/memfs/lib/volume.js:2047:17)
    at FsReadStream._destroy (.../Desktop/wibe-studio/node_modules/memfs/lib/volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at class_1.destroy (node:internal/streams/destroy:83:5)
    at class_1.<anonymous> (.../Desktop/wibe-studio/node_modules/memfs/lib/volume.js:1962:22)
    at class_1.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on class_1 instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTick

**Comment by codebucks27** [comment]
Based on the error message you provided, it appears that the issue might be related to a couple of different factors:

It could be **File System Issues**: The error message `Cannot set property closed of # which has only a getter at FsReadStream.close (.../Desktop/wibe-studio/node_modules/memfs/lib/volume.js:2047:17)` points to a potential issue with the in-memory file system (memfs) that your project is using. This could be caused by a bug or a compatibility issue with the version of Node.js you're using. You can try to update libraries to latest version and use 'Node.js > 18' version. If you still face the same issue remove the ;node_moduels; and ;package-lock.json; file then reinstall all the dependancies. 

If you've tried these steps and the issue persists, please provide more details about your project setup, such as the dependencies you're using, the version of Node.js, and any relevant code snippets related to the issue.
